name: Hello World Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:     
      - name: Say Hello
        run: echo "¡Hola, GitHub Actions!"

      - name: touch file
        run: touch hello.txt

      - name: set text
        run: echo "hola mundo" >> hello.txt

      - name: read file
        run: cat hello.txt




  other:
    runs-on: ubuntu-latest
    steps:     
      - name: LS
        run: ls -al
