name: Hello World Workflow

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:     
      - name: Say Hello
        run: echo "¡Hola, GitHub Actions!"


  other:
    runs-on: ubuntu-latest
    steps:     
      - name: LS
        run: ls -la
